print error in stderr

diff --git a/bin/rotate-path b/bin/rotate-path
--- a/bin/rotate-path
+++ b/bin/rotate-path
@@ -55,7 +55,7 @@ while [[ $# -gt 0 ]]; do
       path=$key
       path_set=true
     else
-      echo "🛑 Invalid argument: $1"
+      echo "🛑 Invalid argument: $1" >&2
       exit 1
     fi
     shift # past argument
@@ -65,7 +65,7 @@ done
 
 # exit if no path
 if [[ -z "$path" ]]; then
-  echo "🛑 No path specified."
+  echo "🛑 No path specified." >&2
   exit 1
 fi
 
diff --git a/bin/ruler b/bin/ruler
--- a/bin/ruler
+++ b/bin/ruler
@@ -54,7 +54,7 @@ while [[ $# -gt 0 ]]; do
       length="$1"
       length_set=true
     else
-      echo "🛑 Invalid argument: $1"
+      echo "🛑 Invalid argument: $1" >&2
       exit 1
     fi
     shift # past argument
@@ -65,13 +65,13 @@ done
 if [[ $length =~ ^[0-9]+$ ]]; then
   :
 else
-  echo "🛑 Invalid length: $length"
+  echo "🛑 Invalid length: $length" >&2
   exit 1
 fi
 
 # make sure length is at least 5
 if [[ $length -lt 20 ]]; then
-  echo "🛑 Invalid length: $length"
+  echo "🛑 Invalid length: $length" >&2
   exit 1
 fi
 
@@ -91,7 +91,7 @@ half_length=$((total_length / 2))
 half_print=$(printf '=%.0s' $(seq 1 "$half_length"))
 
 # Adjust if total_length is odd
-if (( total_length % 2 != 0 )); then
+if ((total_length % 2 != 0)); then
   echo "$half_print $length $half_print="
 else
   echo "$half_print $length $half_print"
diff --git a/bin/swift-build b/bin/swift-build
--- a/bin/swift-build
+++ b/bin/swift-build
@@ -69,7 +69,7 @@ while [[ $# -gt 0 ]]; do
   --config)
     config="$2"
     if [[ $config != "debug" && $config != "release" ]]; then
-      echo "🛑 Unsupported configuration: $config"
+      echo "🛑 Unsupported configuration: $config" >&2
       exit 1
     fi
     config_set=true
@@ -79,7 +79,7 @@ while [[ $# -gt 0 ]]; do
   --arch)
     architecture="$2"
     if [[ $architecture != "arm64" && $architecture != "x86_64" && $architecture != "universal" ]]; then
-      echo "🛑 Unsupported architecture: $architecture"
+      echo "🛑 Unsupported architecture: $architecture" >&2
       exit 1
     fi
     architecture_set=true
@@ -91,7 +91,7 @@ while [[ $# -gt 0 ]]; do
       install_dir="$2"
       # exit if the path is pointing to a file
       if [[ -f $install_dir ]]; then
-        echo "🛑 Error: $install_dir is a valid install path."
+        echo "🛑 Error: $install_dir is a valid install path." >&2
         exit 1
       fi
       shift # past value
@@ -118,12 +118,12 @@ while [[ $# -gt 0 ]]; do
         package_dir="$1"
         package_dir_set=true
       else
-        echo "🛑 Unexpected argument: $1"
+        echo "🛑 Unexpected argument: $1" >&2
         exit 1
       fi
       shift # past argument
     else
-      echo "🛑 Unknown option: $1"
+      echo "🛑 Unknown option: $1" >&2
       exit 1
     fi
     ;;
@@ -144,7 +144,7 @@ if [[ $architecture_set == false ]]; then
 fi
 
 if [[ ! -f "$package_dir/Package.swift" ]]; then
-  echo "🛑 Error: $package_dir is not a Swift package."
+  echo "🛑 Error: $package_dir is not a Swift package." >&2
   exit 1
 fi
 
@@ -178,7 +178,7 @@ fi
 
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
-  echo "🛑 swift build failed."
+  echo "🛑 swift build failed." >&2
   exit 1
 fi
 
@@ -209,7 +209,7 @@ executable_name=$(basename "$executable_path")
 echo ""
 echo "➡️  Strip $executable_name"
 if ! strip "$executable_path"; then
-  echo "🛑 Failed to strip $executable_name"
+  echo "🛑 Failed to strip $executable_name" >&2
   exit 1
 fi
 
@@ -219,9 +219,10 @@ echo "➡️  Copying $executable_name into ${CYAN}$package_dir/Products/$execut
 if [[ -f "$package_dir/Products/$executable_name" && $force == false ]]; then
   echo "⚠️  A binary already exists at: ${YELLOW}$package_dir/Products/$executable_name${NORMAL}"
 
-  reply=""; prompt "Do you want to replace it?" "reply=\"y\"" "reply=\"n\"" "reply=\"n\""
+  reply=""
+  prompt "Do you want to replace it?" "reply=\"y\"" "reply=\"n\"" "reply=\"n\""
   if [[ ! $reply =~ ^[Yy]$ ]]; then
-    echo "🛑 Aborted."
+    echo "🛑 Aborted." >&2
     exit 1
   fi
 fi
@@ -231,26 +232,27 @@ echo "✅ Copied $executable_name into ${GREEN}$package_dir/Products/$executable
 # verify the binary has the correct architecture
 if [[ $architecture == "universal" ]]; then
   if ! lipo "$package_dir/Products/$executable_name" -verify_arch x86_64 arm64; then
-    echo "🛑 The binary does not have the correct architecture."
+    echo "🛑 The binary does not have the correct architecture." >&2
     exit 1
   fi
 else
   if ! lipo "$package_dir/Products/$executable_name" -verify_arch "$architecture"; then
-    echo "🛑 The binary does not have the correct architecture."
+    echo "🛑 The binary does not have the correct architecture." >&2
     exit 1
   fi
 fi
 
 if [[ $should_install == true ]]; then
-  echo "" 
+  echo ""
   echo "➡️  Installing $executable_name to ${CYAN}$install_dir/$executable_name${NORMAL}"
   # if file exists, prompt for confirmation
   if [[ -f "$install_dir/$executable_name" && $force == false ]]; then
     echo "⚠️  A binary already exists at: ${YELLOW}$install_dir/$executable_name${NORMAL}"
 
-    reply=""; prompt "Do you want to replace it?" "reply=\"y\"" "reply=\"n\"" "reply=\"n\""
+    reply=""
+    prompt "Do you want to replace it?" "reply=\"y\"" "reply=\"n\"" "reply=\"n\""
     if [[ ! $reply =~ ^[Yy]$ ]]; then
-      echo "🛑 Aborted."
+      echo "🛑 Aborted." >&2
       exit 1
     fi
   fi
@@ -263,5 +265,5 @@ cd "$current_dir" || (echo "Failed to navigate to $current_dir" && exit 1)
 # References:
 # - https://liamnichols.eu/2020/08/01/building-swift-packages-as-a-universal-binary.html
 # - https://scriptingosx.com/category/swift/
-# - build swift files directly: 
+# - build swift files directly:
 #   - `xcrun -sdk macosx swiftc main.swift -o executable`
diff --git a/bin/xcode-commands/subcommands/xcode-project-file-name b/bin/xcode-commands/subcommands/xcode-project-file-name
--- a/bin/xcode-commands/subcommands/xcode-project-file-name
+++ b/bin/xcode-commands/subcommands/xcode-project-file-name
@@ -49,7 +49,7 @@ while [[ $# -gt 0 ]]; do
     exit 0
     ;;
   *)
-    echo "🛑 Invalid argument: $key"
+    echo "🛑 Invalid argument: $key" >&2
     exit 1
     ;;
   esac
diff --git a/bin/xcode-commands/subcommands/xcode-project-marketing-versions b/bin/xcode-commands/subcommands/xcode-project-marketing-versions
--- a/bin/xcode-commands/subcommands/xcode-project-marketing-versions
+++ b/bin/xcode-commands/subcommands/xcode-project-marketing-versions
@@ -58,7 +58,7 @@ while [[ $# -gt 0 ]]; do
       project_name_set=true
       shift # past argument
     else
-      echo "🛑 Invalid argument: $1"
+      echo "🛑 Invalid argument: $1" >&2
       exit 1
     fi
     ;;
@@ -80,7 +80,7 @@ pbxproj_path="$project_file_name"/project.pbxproj
 
 # confirm project_file_name exists
 if [[ ! -d $project_file_name ]]; then
-  echo "🛑 No project file named $project_file_name found in the current directory."
+  echo "🛑 No project file named $project_file_name found in the current directory." >&2
   exit 1
 fi
 
diff --git a/bin/xcode-commands/xcode b/bin/xcode-commands/xcode
--- a/bin/xcode-commands/xcode
+++ b/bin/xcode-commands/xcode
@@ -59,7 +59,7 @@ fi
 subcommand="$SCRIPT_DIR/xcode-commands/subcommands/xcode-$subcommand"
 
 if [[ ! -f $subcommand ]]; then
-  echo "🛑 Invalid subcommand: $subcommand"
+  echo "🛑 Invalid subcommand: $subcommand" >&2
   exit 1
 fi
 
